package bankapp.domain.models;

public enum Role {
    NATURALCLIENT,
    BUSINESSCLIENT,
    CASHIER,
    SERVICEADVISOR,
    PRODUCTADVISOR,
    COMPANYEMPLOYEE,
    COMPANYSUPERVISOR,
    BACKOFFICE
}