package bankapp.domain.models;

public enum Role {
    NATURALCLIENT,
    LEGALREPRESENTATIVE,
    BUSINESSADMINISTRATOR,
    CASHIER,
    SERVICEADVISOR,
    PRODUCTADVISOR,
    ACCOUNTEXECUTIVE,
    COMPANYOPERATION,
    APPROVAL,
    RISK,
    COMPLIANCE,
    BACKOFFICE
}